apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-app-backup
spec:
  schedule: "{{ .Values.backup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: alpine
              command: ["/bin/sh", "-c"]
              args:
                - |
                  date >> /backup/backup.log
                  echo "Backup done" >> /backup/backup.log
              volumeMounts:
                - name: backup
                  mountPath: /backup
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: demo-app-data
